name: Maven test

on:
  push:
    branches:
     - 'feature/**'

jobs:
  maven-run-test:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Run unit tests with Maven
      run: ./mvnw clean test
